development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: stevedocsbasicv2_db_1

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

production:
  url:  <%= ENV["DATABASE_URL"] %>
  adapter: postgresql
  encoding: unicode
  database: stevedocs_basic_v2_production
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  username: stevedocs_basic_v2
  password: <%= ENV['STEVEDOCS_BASIC_V2_DATABASE_PASSWORD'] %>
