development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: stevedocsbasicv2_db_1

test:
  <<: *default
  database: stevedocsbasicv2_test


production:
  <<: *default
  database: stevedocs_basic_v2_production
  username: stevedocs_basic_v2
  password: <%= ENV['STEVEDOCS_BASIC_V2_DATABASE_PASSWORD'] %>
